# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Λlex's "
weight = 1

#[fr]
#languageName = "French"
#languagedirection = "ltr"
#title = "HelveticAlex - Français"
#weight = 2
