# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "English"
weight = 1

[fr]
languageName = "French"
languagedirection = "ltr"
title = "Français"
weight = 2
